import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  console.log(data);

  const postTitle = data.map((post) => {
    return(
      <h4 key={post.id}>{post.title.rendered}</h4>
    )
  })


  return (
    <>
      <Head>
        <title>WP + nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        

      {postTitle}
        

        
      </main>
    </>
  )
}

export async function getServerSideProps(context) {
  const res  = await fetch(`https://nextwp.hadiul-islam.me/wp-json/wp/v2/posts`)
  const data = await res.json()

  if(!data) {
    return {
      notFound: true
    }
  }

  return {
    props: {
      data
    }
  }
  
}