import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { getPosts } from '../utils/wordpress'
import Post from '../components/Post'
import MainHeader from '../components/layout/main-header'


const inter = Inter({ subsets: ['latin'] })

export default function Home({ posts }) {

  const postBox = posts.map((post => {
    return (
      <>
        <Post key={post.id} post={post} />
      </>
    )
  }))




  return (
    <>
      <Head>
        <title>WP + nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainHeader title="Dev Blog" subTitle="Code smarter, not harder: Insights and tips for developers" />

        <div className='container px-4 px-lg-5'>
          <div className="row gx-4 gx-lg-5 justify-content-center">
            <div className="col-md-10 col-lg-8 col-xl-7">
              {postBox}
            </div>
          </div>
        </div>


      </main>
    </>
  )
}

export async function getStaticProps(params) {
  const posts = await getPosts()
  return {
    props: {
      posts
    }, 
  }
}