import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { getPosts } from '../utils/wordpress'
import Post from '../components/Post'


const inter = Inter({ subsets: ['latin'] })

export default function Home({posts}) {
  console.log(posts);

  

  const postBox = posts.map((post => {
    return(
      <Post post={post} />
    )
  }))




  return (
    <>
      <Head>
        <title>WP + nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Dev Blog</h1>

      {postBox}

        
      </main>
    </>
  )
}

export async function getStaticProps(params) {
  const posts = await getPosts()
  return {
    props: {
      posts
    }, // will be passed to the page component as props
  }
}